on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      VERSION: "2"
      KEY: ${{ secrets.KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ready to deploy the code
        run: echo "Ready to deploy the code of the version $KEY"

      - name: Testing the secrets
        run: echo "Ready to deploy the code of the version $VERSION"
